"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import {
  Loader2,
  Mail,
  FileText,
  Download,
  User,
  Calendar,
  DollarSign,
  StickyNote,
  Edit3,
  Trash2,
  FileDown
} from "lucide-react";

import { motion, AnimatePresence } from "framer-motion";
import { toast } from "react-toastify";

interface AdvanceItem {
  tanggal: string;
  jumlah: string;
  keterangan: string;
}

export default function AdvanceFormPage() {
  const [items, setItems] = useState<AdvanceItem[]>([]);
  const [email, setEmail] = useState("");
  const [namaPemohon, setNamaPemohon] = useState("");
  const [input, setInput] = useState<AdvanceItem>({
    tanggal: "",
    jumlah: "",
    keterangan: "",
  });
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [loading, setLoading] = useState(false);

  const [pdfUrl, setPdfUrl] = useState<string>("");

  const formatRupiah = (value: string | number) => {
    const number = typeof value === "string" ? parseFloat(value) : value;
    return isNaN(number)
      ? "-"
      : new Intl.NumberFormat("id-ID", {
          style: "currency",
          currency: "IDR",
          minimumFractionDigits: 0,
        }).format(number);
  };

  const totalAmount = items.reduce((acc, item) => acc + Number(item.jumlah), 0);

  const handleAddItem = () => {
    if (!input.tanggal || !input.jumlah || !input.keterangan) return;

    if (editingIndex !== null) {
      const updated = [...items];
      updated[editingIndex] = input;
      setItems(updated);
      setEditingIndex(null);
    } else {
      setItems([...items, input]);
    }

    setInput({ tanggal: input.tanggal, jumlah: "", keterangan: "" });
  };

  const handleEditItem = (index: number) => {
    setInput(items[index]);
    setEditingIndex(index);
  };

  const handleDeleteItem = (index: number) => {
    const updated = items.filter((_, i) => i !== index);
    setItems(updated);
  };

  const generatePdf = async (): Promise<{ dataUrl: string; blob: Blob }> => {
    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  
    // Logo (opsional, bisa letakkan di folder public/logo.png)
    // try {
    //   const img = new Image();
    //   img.src = "/logo.png"; // Pastikan logo berada di public/logo.png
    //   await new Promise<void>((resolve) => {
    //     img.onload = () => resolve();
    //   });
    //   doc.addImage(img, "PNG", 15, 10, 20, 20); // x, y, width, height
    // } catch (err) {
    //   console.warn("Logo tidak ditemukan atau gagal dimuat");
    // }
  
    // Nama Perusahaan
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(30, 64, 175); // Navy Blue
    doc.text("PT KARYA BAKTI NUSINDO", 105, 15, { align: "center" });
  
    // Alamat dan kontak
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60); // Dark gray
    doc.text(
      "Jl. Arjuna Utara No.12, RT.11/RW.2, Tj. Duren Sel., Grogol Petamburan,\nJakarta Barat, DKI Jakarta 11470",
      105,
      21,
      { align: "center", maxWidth: 180 }
    );
    // doc.text("Telp: (021) 12345678 | Email: info@herlambangmedicenter.co.id", 105, 28, {
    //   align: "center",
    // });
  
    // Garis bawah header
    doc.setDrawColor(30, 64, 175);
    doc.setLineWidth(0.5);
    doc.line(10, 34, 200, 34);
  
    // Judul Laporan
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("LAPORAN PERMINTAAN ADVANCE", 105, 42, { align: "center" });
  
    // Nama pemohon
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(0); // hitam
    doc.text("Nama Pemohon:", 14, 50);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(30, 64, 175); // biru navy
    doc.text(namaPemohon || "-", 50, 50);
    
    // Garis bawah sebagai pembatas antara header dan tabel
    doc.setDrawColor(225);
    doc.setLineWidth(0.3);
    doc.line(10, 52, 200, 52);
    
  
    // Tabel isi
    autoTable(doc, {
      startY: 56,
      head: [["Tanggal", "Jumlah", "Keterangan"]],
      body: items.map((item) => [
        item.tanggal,
        formatRupiah(item.jumlah),
        item.keterangan,
      ]),
      theme: "striped",
      headStyles: { fillColor: [30, 64, 175], textColor: 255 },
      alternateRowStyles: { fillColor: [241, 245, 249] },
      margin: { left: 10, right: 10 },
    });
  
    // Total
    const y = doc.lastAutoTable?.finalY ?? 60;
    doc.setFontSize(12);
    doc.setTextColor("#1e293b");
    doc.text(`Total: ${formatRupiah(totalAmount)}`, 14, y + 10);
  
    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by Herlambang System © 2025", 105, pageHeight - 10, {
      align: "center",
    });
  
    const blob = doc.output("blob");
    const dataUrl = doc.output("datauristring");
    setPdfUrl(URL.createObjectURL(blob));
    return { dataUrl, blob };
  };
  

  const handleExportExcel = () => {
    const ws = XLSX.utils.json_to_sheet(
      items.map((item) => ({
        Tanggal: item.tanggal,
        Jumlah: item.jumlah,
        Keterangan: item.keterangan,
      }))
    );
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Permintaan Advance");
    XLSX.writeFile(wb, "permintaan-advance.xlsx");
  };

  const handleSendEmail = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/advance/addEmailSender", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email,
          namaPemohon,
          data: items,
        }),
      });

      const result = await res.json();
      if (result.status === "success") {
        toast.success("✅ Email berhasil dikirim dan data disimpan!");
      } else {
        toast.error("❌ Gagal: " + result.message);
      }
    } catch {
      toast.error("❌ Terjadi kesalahan saat mengirim data");
    }
    setLoading(false);
  };

  const handleExportPDF = async () => {
    const { blob } = await generatePdf();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "permintaan-advance.pdf";
    a.click();
  };

  return (
    <div className="p-4 max-w-4xl mx-auto text-gray-800 dark:text-gray-100 relative">
            <AnimatePresence>
        {loading && (
          <motion.div
            className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <motion.div
              className="bg-white dark:bg-gray-800 px-6 py-4 rounded-xl shadow-lg flex items-center gap-4"
              initial={{ scale: 0.8 }}
              animate={{ scale: 1 }}
              exit={{ scale: 0.8 }}
            >
              <Loader2 className="animate-spin text-blue-600 w-6 h-6" />
              <span className="text-sm font-medium">
                Mengirim data ke server...
              </span>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      <h1 className="text-2xl font-bold text-center mb-6">
        💰 Form Permintaan Advance
      </h1>

      <div className="bg-white dark:bg-gray-900 shadow-md rounded-lg p-6 grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div className="relative">
            <User className="absolute left-3 top-3 text-gray-400 w-5 h-5 " />
            <input
              type="text"
              value={namaPemohon}
              onChange={(e) => setNamaPemohon(e.target.value)}
              placeholder="Nama Pemohon"
              className="pl-10 border rounded p-2 w-full dark:bg-gray-800 dark:border-gray-600"
            />
          </div>
          <div className="relative">
            <Calendar className="absolute left-3 top-3 text-gray-400 w-5 h-5" />
            <input
              type="date"
              value={input.tanggal}
              onChange={(e) => setInput({ ...input, tanggal: e.target.value })}
              className="pl-10 border rounded p-2 w-full dark:bg-gray-800 dark:border-gray-600"
            />
          </div>
          <div className="relative">
            <DollarSign className="absolute left-3 top-3 text-gray-400 w-5 h-5" />
            <input
              type="number"
              placeholder="Jumlah"
              value={input.jumlah}
              onChange={(e) => setInput({ ...input, jumlah: e.target.value })}
              className="pl-10 border rounded p-2 w-full dark:bg-gray-800 dark:border-gray-600"
            />
          </div>
          <div className="relative">
            <StickyNote className="absolute left-3 top-3 text-gray-400 w-5 h-5" />
            <textarea
              placeholder="Keterangan"
              value={input.keterangan}
              onChange={(e) => setInput({ ...input, keterangan: e.target.value })}
              className="pl-10 border rounded p-2 w-full dark:bg-gray-800 dark:border-gray-600"
            />
          </div>
          <button
            onClick={handleAddItem}
            className="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600 w-full"
          >
            {editingIndex !== null ? "Perbarui Data" : "Tambahkan"}
          </button>
          <div className="relative">
            <Mail className="absolute left-3 top-3 text-gray-400 w-5 h-5" />
            <input
              type="email"
              placeholder="Email tujuan"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="pl-10 border p-2 rounded w-full dark:bg-gray-800 dark:border-gray-600"
            />
          </div>
        </div>

        <div className="space-y-4">
          <h2 className="text-lg font-semibold">📋 Daftar Permintaan</h2>
          {items.length === 0 ? (
            <p className="text-gray-500 dark:text-gray-400 animate-pulse">Belum ada permintaan.</p>
          ) : (
            <ul className="space-y-3">
              {items.map((item, i) => (
                <motion.li
                  key={i}
                  className="border p-3 rounded bg-gray-50 dark:bg-gray-800 dark:border-gray-700"
                  initial={{ opacity: 0, scale: 0.9 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.9 }}
                  transition={{ duration: 0.2 }}
                >
                  <div className="flex justify-between items-center">
                    <div>
                      <p>
                        <strong>{item.tanggal}</strong> - {formatRupiah(item.jumlah)}
                      </p>
                      <p className="text-sm text-gray-600 dark:text-gray-300">
                        {item.keterangan}
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <button
                        className="text-blue-500 hover:text-blue-700"
                        onClick={() => handleEditItem(i)}
                      >
                        <Edit3 className="w-4 h-4" />
                      </button>
                      <button
                        className="text-red-500 hover:text-red-700"
                        onClick={() => handleDeleteItem(i)}
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </motion.li>
              ))}
            </ul>
          )}
          <div className="pt-2 text-right font-semibold">
            Total: {formatRupiah(totalAmount)}
          </div>
        </div>
      </div>

      <div className="flex flex-wrap justify-end gap-4 mt-6">
        {pdfUrl && (
          <a
            href={pdfUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="bg-gray-700 text-white px-4 py-2 rounded-xl hover:bg-gray-800 flex items-center gap-2"
          >
            <FileText className="w-8 h-8 rounded-full bg-white p-2 text-black" /> Preview PDF
          </a>
        )}
        <button
          onClick={handleExportPDF}
          disabled={items.length === 0}
          className="bg-blue-600 text-white px-4 py-2 rounded-xl hover:bg-blue-700 flex items-center gap-2"
        >
          <Download className="w-8 h-8 rounded-full bg-white p-2 text-black" /> Export PDF
        </button>
        <button
          onClick={handleExportExcel}
          disabled={items.length === 0}
          className="bg-emerald-600 text-white px-4 py-2 rounded-xl hover:bg-emerald-700 flex items-center gap-2"
        >
          <FileDown className="w-8 h-8 rounded-full bg-white p-2 text-black" /> Export Excel
        </button>
        <button
          onClick={handleSendEmail}
          disabled={items.length === 0 || !email}
          className="bg-indigo-600 text-white px-4 py-2 rounded-xl hover:bg-indigo-700 flex items-center gap-2"
        >
          <Mail className="w-8 h-8 rounded-full bg-white p-2 text-black" /> Kirim ke Email
        </button>
      </div>
    </div>
  );
}
