// app/layout.tsx atau app/root-layout.tsx
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider"; // pastikan ini benar
import { Toaster } from "@/components/ui/toaster";
import { AppUpdateBanner } from "@/components/app/AppUpdateBanner";
import { ServiceWorkerRegister } from "@/components/app/ServiceWorkerRegister";

export const metadata = {
  title: "myBook-herlambang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster />
          <ServiceWorkerRegister />
          <AppUpdateBanner />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
